# Autogenerated bulkloader.yaml file.
# At a minimum address the items marked with TODO:
#  * Fill in connector and connector_options
#  * Review the property_map.
#    - Ensure the 'external_name' matches the name of your CSV column,
#      XML tag, etc.
#    - Check that __key__ property is what you want. Its value will become
#      the key name on import, and on export the value will be the Key
#      object.  If you would like automatic key generation on import and
#      omitting the key on export, you can remove the entire __key__
#      property from the property map.

# If you have module(s) with your model classes, add them here. Also
# change the kind properties to model_class.
python_preamble:
- import: base64
- import: re
- import: google.appengine.ext.bulkload.transform
- import: google.appengine.ext.bulkload.bulkloader_wizard
- import: google.appengine.ext.db
- import: google.appengine.api.datastore
- import: google.appengine.api.users

transformers:

- kind: Trainer
  connector: csv
  property_map:
    - property: __key__
      external_name: key
      export_transform: transform.key_id_or_name_as_string

    - property: bio
      external_name: bio
      # Type: Text Stats: 3 properties of this type in this kind.
      import_transform: db.Text

    - property: created
      external_name: created
      # Type: Date/Time Stats: 3 properties of this type in this kind.
      import_transform: transform.import_date_time('%Y-%m-%dT%H:%M:%S')
      export_transform: transform.export_date_time('%Y-%m-%dT%H:%M:%S')

    - property: created_by
      external_name: created_by
      # Type: User Stats: 3 properties of this type in this kind.
      import_transform: transform.none_if_empty(users.User)  # Assumes email address

    - property: email
      external_name: email
      # Type: String Stats: 3 properties of this type in this kind.

    - property: firstName
      external_name: firstName
      # Type: String Stats: 3 properties of this type in this kind.

    - property: lastName
      external_name: lastName
      # Type: String Stats: 3 properties of this type in this kind.

    - property: modified
      external_name: modified
      # Type: Date/Time Stats: 3 properties of this type in this kind.
      import_transform: transform.import_date_time('%Y-%m-%dT%H:%M:%S')
      export_transform: transform.export_date_time('%Y-%m-%dT%H:%M:%S')

    - property: modified_by
      external_name: modified_by
      # Type: User Stats: 3 properties of this type in this kind.
      import_transform: transform.none_if_empty(users.User)  # Assumes email address

    - property: schoolAddress1
      external_name: schoolAddress1
      # Type: String Stats: 3 properties of this type in this kind.

    - property: schoolAddress2
      external_name: schoolAddress2
      # Type: String Stats: 3 properties of this type in this kind.

    - property: schoolAddressCity
      external_name: schoolAddressCity
      # Type: String Stats: 3 properties of this type in this kind.

    - property: schoolAddressState
      external_name: schoolAddressState
      # Type: String Stats: 3 properties of this type in this kind.

    - property: schoolAddressZip
      external_name: schoolAddressZip
      # Type: String Stats: 3 properties of this type in this kind.

    - property: schoolDistrict
      external_name: schoolDistrict
      # Type: String Stats: 3 properties of this type in this kind.

    - property: schoolName
      external_name: schoolName
      # Type: String Stats: 3 properties of this type in this kind.
